<?xml version="1.0" encoding="utf-8"?><Database Name="MeetUp" Class="TempDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tlc-dev-sql01;Initial Catalog=MeetUp;Integrated Security=True" SettingsObjectName="HelloAngularJS_EF.Core.Properties.Settings" SettingsPropertyName="MeetUpConnectionString" Provider="System.Data.SqlClient" />
</Database>